### ISSUE TITLE
Determine whether remove "Tough As Nails" and "Serene Seasons" mods

### ISSUE THREAD

**Issue by SamLam140330** [SamLam140330/DangerousWorld#5]
Duo to the mod has a bug that shows a wrong GUI for the thirst and temperature when you travel to different dimensions. Also, the mod has been abandoned to maintenance the mod of version 1.12.2. Now evaluate to drop "Tough As Nails" and "Serene Seasons" mods in our Modpack.

https://user-images.githubusercontent.com/48656764/127853301-fbaabe73-a06e-4ec9-8232-c9af554ac1d7.mp4

**Comment by LHemon412** [comment]
I agree that "Tough As Nails" and "Serene Seasons" should be removed.
Apart from the thirst bug, the mod lacks a better way to purify water (e.g. water purification machine), so obtaining purified water requires repetitive manual crafting. Also, the hydration level drops rapidly in nether, so this mod is adding much difficulty in exploring nether without providing a reasonable way to tackle it.
On the other hand, the mod "Serene Seasons" limits crops to be only able to fertile in specific seasons, and each season lasts for 8 in-game days, so it would slow down players' progress in crafting different foods significantly.
Despite several measures that can be taken to ignore the season restrictions (e.g. greenhouse glasses, planting at y < 48), it is still adding too much difficulty in terms of obtaining stable food sources at early game.
"Serene Seasons" mod is also probably one of the reasons causing #6 .

**Comment by tomato747** [comment]
Dangerous ar ma
